# Generated by Django 4.2.1 on 2023-06-07 12:03

from django.db import migrations, models
import main.utils


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=200, null=True, verbose_name='Информация'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[main.utils.validate_phone_number], verbose_name='Номер телефона'),
        ),
    ]
