# Generated by Django 4.2.1 on 2023-06-07 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_profile_description_alter_profile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='bith_data',
            new_name='birth_data',
        ),
    ]
